"""Rule-based WAM runtime primitives for the first implementation pass."""

from .runtime import (
    CoopRequest,
    MotionPredictionRecord,
    NotableObjectRecord,
    ObjectState,
    WAMPolicy,
    build_coop_request,
    build_placeholder_policy,
    predict_notable_motion,
    select_notable_objects,
)
from .debug_recording import (
    ActorSnapshot,
    WAMNotableDebugRecorder,
    carla_actor_bbox_footprint,
    future_sample_offsets,
    future_sample_step_offsets,
    predicted_future_waypoints,
    snapshot_from_carla_actor,
)
from .bev import (
    BEV_CHANNEL_NAMES,
    BEV_NUM_CHANNELS,
    BevSpec,
    WAMBevDecoder,
    bev_iou,
    bev_reconstruction_loss,
    rasterize_bev,
)
from .coverage import (
    COVERAGE_CHANNEL_NAMES,
    COVERAGE_NUM_CHANNELS,
    CoverageConfig,
    build_coverage_raster,
    coverage_metrics,
    route_corridor_polyline,
)
from .graph import (
    EDGE_ATTR_DIMS,
    EDGE_TYPES,
    MODALITIES,
    MODALITY_TO_ID,
    NODE_TYPES,
    OBJECT,
    OBJECT_CLASSES,
    OBJECT_STATE_DIM,
    OBS_OBJ,
    OBS_OBJ_EDGE_DIM,
    OBS_SCALAR_DIM,
    OBSERVATION,
    VEH_OBS,
    VEH_VEH,
    VEH_VEH_EDGE_DIM,
    VEHICLE,
    WAM_METADATA,
    FusedObjects,
    GraphBuildSpec,
    ObservationNodeInput,
    VehicleNodeInput,
    build_wam_hetero_graph,
    detection_confidence,
    fuse_injected_objects,
    hetero_graph_stats,
    vehicle_state_dim,
)
from .graph_model import (
    WAMGraphModelConfig,
    WAMHeteroGraphEmbedding,
    WAMHeteroGraphEncoder,
    WAMHeteroGraphNet,
)
from .heads import (
    GaussianTrajectoryHead,
    NotableObjectHead,
    WAMPerceptionConfig,
    WAMPerceptionModel,
    WAMTemporalEncoder,
    align_object_history,
    gaussian_trajectory_nll,
    perception_loss,
    perception_metrics,
    policy_uncertainty,
    trajectory_ade_fde,
)
from .targets import (
    TrajectoryTargetBuffer,
    build_trajectory_targets,
)
from .flow_matching import (
    SinusoidalTimeEmbedding,
    WAMBSContextEncoder,
    WAMFlowMatchingConfig,
    WAMFlowMatchingUWM,
    WAMGraphContextPool,
    WAMUnifiedWorldModel,
    decode_policy_vector,
    encode_policy,
    encode_policy_chunk,
    flow_matching_loss,
    interpolate,
    pad_condition_tokens,
    sample_training_batch,
)
from .stage2 import (
    WAMFlowDataset,
    WAMStage2Config,
    WAMStage2Trainer,
    collate_flow_samples,
    decode_chunk_to_wampolicy,
    uwm_propose_chunks,
    load_wam_uwm,
    make_flow_sample,
    wam_configs_from_env,
)
from .flow_recorder import WAMFlowDataRecorder
from .action_chunk import (
    ActionChunk,
    SubAction,
    action_chunk_to_comm_segments,
    enumerate_candidate_chunks,
    local_only_chunk,
    sub_action_to_comm_policy,
)
from .lyapunov import (
    BudgetVirtualQueue,
    CostRateBreakdown,
    LinkQueue,
    LyapunovConfig,
    LyapunovState,
    action_cost_rate,
)
from .risk_controller import (
    ControlDecision,
    RiskControlConfig,
    TrackedObject,
    advance_pose_along_route,
    cumulative_lengths,
    object_future_positions,
    point_at_arclength,
    risk_of_accel,
    select_accel,
)
from .rollout_scorer import RolloutContext, RolloutResult, WorldActionScorer
from .wam_mdp import (
    ActionSpec,
    MDPConfig,
    encode_subaction,
    decode_subaction,
    subaction_from_metadata,
    subaction_cost,
    eq12_motion_uncertainty,
)
from .wam_rssm import RSSM, RSSMConfig
from .wam_world_model import WAMWorldModel, WorldModelConfig, symlog, symexp
from .wam_actor_critic import ActorCriticConfig, Critic, FactorizedActor, WAMActorCritic, lambda_return
from .wam_planner import WAMDreamerPolicy, load_dreamer_policy
from .lyapunov_scheduler import (
    LyapunovScheduler,
    ReferenceTrajectory,
    SchedulerConfig,
    candidate_chunks,
    next_epoch_step,
    select_action_chunk,
)
from .stage1 import (
    WAMStage1Config,
    WAMStage1Dataset,
    WAMStage1Trainer,
    collate_stage1_samples,
    init_encoder_from_stage1,
    make_stage1_sample,
    wam_stage1_configs_from_env,
)
from .stage1_recorder import WAMStage1DataRecorder, perception_labels_at_t, subaction_from_policy, union_object_ids, valid_object_ids
from .stage1_policy import (
    COMM_REPLAY_METADATA_FIELDS,
    STAGE1_POLICY_TYPES,
    WAMStage1CommunicationPolicyDataRecorder,
    WAMStage1PolicyDataRecorder,
    bev_payload_bytes,
    build_stage1_policy_graph,
    enumerate_stage1_policies,
    evaluate_stage1_uncertainty_rows,
    make_stage1_policy_metadata,
    objlist_payload_bytes,
    policy_key,
    policy_to_dict,
    visible_object_ids_by_vehicle,
)
from .stage1_policy_viz import (
    add_metric_delta,
    load_policy_uncertainty_csv,
    policy_label,
    summarize_policy_breakdown,
    summarize_policies,
    write_policy_uncertainty_html,
    write_policy_uncertainty_summary_csv,
)
from .graph_timeline_viz import (
    BevOptions,
    append_record_jsonl,
    group_records_to_frames,
    build_episode_uncertainty_series,
    hetero_graph_to_record,
    layout_layered,
    load_records_jsonl,
    render_graph_matplotlib,
    write_graph_frames_png,
    write_graph_timeline_gif,
    write_graph_timeline_html,
)

__all__ = [
    "ActorSnapshot",
    "CoopRequest",
    "MotionPredictionRecord",
    "NotableObjectRecord",
    "ObjectState",
    "WAMPolicy",
    "WAMNotableDebugRecorder",
    "build_coop_request",
    "build_placeholder_policy",
    "carla_actor_bbox_footprint",
    "future_sample_offsets",
    "future_sample_step_offsets",
    "predict_notable_motion",
    "predicted_future_waypoints",
    "select_notable_objects",
    "snapshot_from_carla_actor",
    # per-vehicle visibility-aware BEV (§5.3 / §14 / §15.4)
    "BEV_CHANNEL_NAMES",
    "BEV_NUM_CHANNELS",
    "BevSpec",
    "WAMBevDecoder",
    "bev_iou",
    "bev_reconstruction_loss",
    "rasterize_bev",
    # route-corridor coverage uncertainty
    "COVERAGE_CHANNEL_NAMES",
    "COVERAGE_NUM_CHANNELS",
    "CoverageConfig",
    "build_coverage_raster",
    "coverage_metrics",
    "route_corridor_polyline",
    # hetero graph construction (§4-§7 + Edge Representation Update)
    "EDGE_ATTR_DIMS",
    "EDGE_TYPES",
    "MODALITIES",
    "MODALITY_TO_ID",
    "NODE_TYPES",
    "OBJECT",
    "OBJECT_CLASSES",
    "OBJECT_STATE_DIM",
    "OBS_OBJ",
    "OBS_OBJ_EDGE_DIM",
    "OBS_SCALAR_DIM",
    "OBSERVATION",
    "VEH_OBS",
    "VEH_VEH",
    "VEH_VEH_EDGE_DIM",
    "VEHICLE",
    "WAM_METADATA",
    "GraphBuildSpec",
    "ObservationNodeInput",
    "VehicleNodeInput",
    "build_wam_hetero_graph",
    "detection_confidence",
    "fuse_injected_objects",
    "FusedObjects",
    "hetero_graph_stats",
    "vehicle_state_dim",
    # graph embedding + HGT encoder (§5, §9)
    "WAMGraphModelConfig",
    "WAMHeteroGraphEmbedding",
    "WAMHeteroGraphEncoder",
    "WAMHeteroGraphNet",
    # temporal encoder + task heads (§10, §11) + losses / reward (§15, §11.2)
    "GaussianTrajectoryHead",
    "NotableObjectHead",
    "WAMPerceptionConfig",
    "WAMPerceptionModel",
    "WAMTemporalEncoder",
    "align_object_history",
    "gaussian_trajectory_nll",
    "perception_loss",
    "perception_metrics",
    "policy_uncertainty",
    "trajectory_ade_fde",
    # ground-truth trajectory targets (§15.2)
    "TrajectoryTargetBuffer",
    "build_trajectory_targets",
    # BS-centric diffusion unified world model (Design Update §2-§8, §13)
    "SinusoidalTimeEmbedding",
    "WAMBSContextEncoder",
    "WAMFlowMatchingConfig",
    "WAMFlowMatchingUWM",
    "WAMGraphContextPool",
    "WAMUnifiedWorldModel",
    "decode_policy_vector",
    "encode_policy",
    "encode_policy_chunk",
    "flow_matching_loss",
    "interpolate",
    "pad_condition_tokens",
    "sample_training_batch",
    # stage-2 training pipeline (§16.2)
    "WAMFlowDataset",
    "WAMFlowDataRecorder",
    "WAMStage2Config",
    "WAMStage2Trainer",
    "collate_flow_samples",
    "decode_chunk_to_wampolicy",
    "uwm_propose_chunks",
    "load_wam_uwm",
    "make_flow_sample",
    "wam_configs_from_env",
    # action-chunk data model + heuristic candidates + CommPolicy segmentation (V2X paper Sec I.B)
    "ActionChunk",
    "SubAction",
    "action_chunk_to_comm_segments",
    "enumerate_candidate_chunks",
    "local_only_chunk",
    "sub_action_to_comm_policy",
    # Lyapunov queues (Q_m eq27, Z eq35) + per-frame cost-rate (eq41/42)
    "BudgetVirtualQueue",
    "CostRateBreakdown",
    "LinkQueue",
    "LyapunovConfig",
    "LyapunovState",
    "action_cost_rate",
    # risk-aware speed controller (Sec I.E, eqs 29-32)
    "ControlDecision",
    "RiskControlConfig",
    "TrackedObject",
    "advance_pose_along_route",
    "cumulative_lengths",
    "object_future_positions",
    "point_at_arclength",
    "risk_of_accel",
    "select_accel",
    # world-action rollout scorer (Sec III): per-slot Ũ + predicted comm load
    "RolloutContext",
    "RolloutResult",
    "WorldActionScorer",
    # cooperative-perception semi-MDP (Dreamer redesign, P1): reward + action codec + eq-12 U
    "ActionSpec",
    "MDPConfig",
    "encode_subaction",
    "decode_subaction",
    "subaction_from_metadata",
    "subaction_cost",
    "eq12_motion_uncertainty",
    # Dreamer world model (P2): RSSM + encoder/reward/cont/BEV heads
    "RSSM",
    "RSSMConfig",
    "WAMWorldModel",
    "WorldModelConfig",
    "symlog",
    "symexp",
    # Dreamer actor-critic (P3): imagination policy + value
    "ActorCriticConfig",
    "FactorizedActor",
    "Critic",
    "WAMActorCritic",
    "lambda_return",
    # Dreamer online planner (P4)
    "WAMDreamerPolicy",
    "load_dreamer_policy",
    # Lyapunov-guided policy search (Sec IV, Algorithm 1): P2 solver + event-driven replan
    "LyapunovScheduler",
    "ReferenceTrajectory",
    "SchedulerConfig",
    "candidate_chunks",
    "next_epoch_step",
    "select_action_chunk",
    # stage-1 training pipeline (§16.1) + warm-start
    "WAMStage1Config",
    "WAMStage1Dataset",
    "WAMStage1DataRecorder",
    "WAMStage1CommunicationPolicyDataRecorder",
    "WAMStage1PolicyDataRecorder",
    "COMM_REPLAY_METADATA_FIELDS",
    "WAMStage1Trainer",
    "STAGE1_POLICY_TYPES",
    "bev_payload_bytes",
    "build_stage1_policy_graph",
    "collate_stage1_samples",
    "subaction_from_policy",
    "enumerate_stage1_policies",
    "evaluate_stage1_uncertainty_rows",
    "add_metric_delta",
    "init_encoder_from_stage1",
    "load_policy_uncertainty_csv",
    "make_stage1_policy_metadata",
    "make_stage1_sample",
    "objlist_payload_bytes",
    "policy_label",
    "policy_key",
    "policy_to_dict",
    "summarize_policy_breakdown",
    "summarize_policies",
    "perception_labels_at_t",
    "union_object_ids",
    "valid_object_ids",
    "visible_object_ids_by_vehicle",
    "wam_stage1_configs_from_env",
    "write_policy_uncertainty_html",
    "write_policy_uncertainty_summary_csv",
    # per-step cooperative-graph timeline visualization
    "BevOptions",
    "append_record_jsonl",
    "group_records_to_frames",
    "hetero_graph_to_record",
    "build_episode_uncertainty_series",
    "layout_layered",
    "load_records_jsonl",
    "render_graph_matplotlib",
    "write_graph_frames_png",
    "write_graph_timeline_gif",
    "write_graph_timeline_html",
]
