"""Rule-based WAM runtime primitives for the first implementation pass."""

from .runtime import (
    CoopRequest,
    MotionPredictionRecord,
    NotableObjectRecord,
    ObjectState,
    WAMPolicy,
    build_coop_request,
    build_placeholder_policy,
    predict_notable_motion,
    select_notable_objects,
)
from .debug_recording import (
    ActorSnapshot,
    WAMNotableDebugRecorder,
    carla_actor_bbox_footprint,
    future_sample_offsets,
    future_sample_step_offsets,
    predicted_future_waypoints,
    snapshot_from_carla_actor,
)
from .bev import (
    BEV_CHANNEL_NAMES,
    BEV_NUM_CHANNELS,
    BevSpec,
    WAMBevDecoder,
    bev_iou,
    bev_reconstruction_loss,
    rasterize_bev,
)
from .graph import (
    EDGE_ATTR_DIMS,
    EDGE_TYPES,
    MODALITIES,
    MODALITY_TO_ID,
    NODE_TYPES,
    OBJECT,
    OBJECT_CLASSES,
    OBJECT_STATE_DIM,
    OBS_OBJ,
    OBS_OBJ_EDGE_DIM,
    OBS_SCALAR_DIM,
    OBSERVATION,
    VEH_OBS,
    VEH_VEH,
    VEH_VEH_EDGE_DIM,
    VEHICLE,
    WAM_METADATA,
    GraphBuildSpec,
    ObservationNodeInput,
    VehicleNodeInput,
    build_wam_hetero_graph,
    hetero_graph_stats,
    vehicle_state_dim,
)
from .graph_model import (
    WAMGraphModelConfig,
    WAMHeteroGraphEmbedding,
    WAMHeteroGraphEncoder,
    WAMHeteroGraphNet,
)
from .heads import (
    GaussianTrajectoryHead,
    NotableObjectHead,
    WAMPerceptionConfig,
    WAMPerceptionModel,
    WAMTemporalEncoder,
    align_object_history,
    gaussian_trajectory_nll,
    perception_loss,
    perception_metrics,
    policy_uncertainty,
    trajectory_ade_fde,
)
from .targets import (
    TrajectoryTargetBuffer,
    build_trajectory_targets,
)
from .flow_matching import (
    SinusoidalTimeEmbedding,
    WAMBSContextEncoder,
    WAMFlowMatchingConfig,
    WAMFlowMatchingUWM,
    WAMGraphContextPool,
    WAMUnifiedWorldModel,
    decode_policy_vector,
    encode_policy,
    encode_policy_chunk,
    flow_matching_loss,
    interpolate,
    pad_condition_tokens,
    sample_training_batch,
)
from .stage2 import (
    WAMFlowDataset,
    WAMStage2Config,
    WAMStage2Trainer,
    collate_flow_samples,
    make_flow_sample,
    wam_configs_from_env,
)
from .flow_recorder import WAMFlowDataRecorder
from .stage1 import (
    WAMStage1Config,
    WAMStage1Dataset,
    WAMStage1Trainer,
    collate_stage1_samples,
    init_encoder_from_stage1,
    make_stage1_sample,
    wam_stage1_configs_from_env,
)
from .stage1_recorder import WAMStage1DataRecorder, valid_object_ids
from .stage1_policy import (
    STAGE1_POLICY_TYPES,
    WAMStage1PolicyDataRecorder,
    bev_payload_bytes,
    build_stage1_policy_graph,
    enumerate_stage1_policies,
    evaluate_stage1_uncertainty_rows,
    make_stage1_policy_metadata,
    objlist_payload_bytes,
    policy_key,
    policy_to_dict,
    visible_object_ids_by_vehicle,
)
from .stage1_policy_viz import (
    add_metric_delta,
    load_policy_uncertainty_csv,
    policy_label,
    summarize_policies,
    write_policy_uncertainty_html,
)
from .graph_timeline_viz import (
    BevOptions,
    append_record_jsonl,
    group_records_to_frames,
    hetero_graph_to_record,
    layout_layered,
    load_records_jsonl,
    render_graph_matplotlib,
    write_graph_frames_png,
    write_graph_timeline_gif,
    write_graph_timeline_html,
)

__all__ = [
    "ActorSnapshot",
    "CoopRequest",
    "MotionPredictionRecord",
    "NotableObjectRecord",
    "ObjectState",
    "WAMPolicy",
    "WAMNotableDebugRecorder",
    "build_coop_request",
    "build_placeholder_policy",
    "carla_actor_bbox_footprint",
    "future_sample_offsets",
    "future_sample_step_offsets",
    "predict_notable_motion",
    "predicted_future_waypoints",
    "select_notable_objects",
    "snapshot_from_carla_actor",
    # per-vehicle visibility-aware BEV (§5.3 / §14 / §15.4)
    "BEV_CHANNEL_NAMES",
    "BEV_NUM_CHANNELS",
    "BevSpec",
    "WAMBevDecoder",
    "bev_iou",
    "bev_reconstruction_loss",
    "rasterize_bev",
    # hetero graph construction (§4-§7 + Edge Representation Update)
    "EDGE_ATTR_DIMS",
    "EDGE_TYPES",
    "MODALITIES",
    "MODALITY_TO_ID",
    "NODE_TYPES",
    "OBJECT",
    "OBJECT_CLASSES",
    "OBJECT_STATE_DIM",
    "OBS_OBJ",
    "OBS_OBJ_EDGE_DIM",
    "OBS_SCALAR_DIM",
    "OBSERVATION",
    "VEH_OBS",
    "VEH_VEH",
    "VEH_VEH_EDGE_DIM",
    "VEHICLE",
    "WAM_METADATA",
    "GraphBuildSpec",
    "ObservationNodeInput",
    "VehicleNodeInput",
    "build_wam_hetero_graph",
    "hetero_graph_stats",
    "vehicle_state_dim",
    # graph embedding + HGT encoder (§5, §9)
    "WAMGraphModelConfig",
    "WAMHeteroGraphEmbedding",
    "WAMHeteroGraphEncoder",
    "WAMHeteroGraphNet",
    # temporal encoder + task heads (§10, §11) + losses / reward (§15, §11.2)
    "GaussianTrajectoryHead",
    "NotableObjectHead",
    "WAMPerceptionConfig",
    "WAMPerceptionModel",
    "WAMTemporalEncoder",
    "align_object_history",
    "gaussian_trajectory_nll",
    "perception_loss",
    "perception_metrics",
    "policy_uncertainty",
    "trajectory_ade_fde",
    # ground-truth trajectory targets (§15.2)
    "TrajectoryTargetBuffer",
    "build_trajectory_targets",
    # BS-centric diffusion unified world model (Design Update §2-§8, §13)
    "SinusoidalTimeEmbedding",
    "WAMBSContextEncoder",
    "WAMFlowMatchingConfig",
    "WAMFlowMatchingUWM",
    "WAMGraphContextPool",
    "WAMUnifiedWorldModel",
    "decode_policy_vector",
    "encode_policy",
    "encode_policy_chunk",
    "flow_matching_loss",
    "interpolate",
    "pad_condition_tokens",
    "sample_training_batch",
    # stage-2 training pipeline (§16.2)
    "WAMFlowDataset",
    "WAMFlowDataRecorder",
    "WAMStage2Config",
    "WAMStage2Trainer",
    "collate_flow_samples",
    "make_flow_sample",
    "wam_configs_from_env",
    # stage-1 training pipeline (§16.1) + warm-start
    "WAMStage1Config",
    "WAMStage1Dataset",
    "WAMStage1DataRecorder",
    "WAMStage1PolicyDataRecorder",
    "WAMStage1Trainer",
    "STAGE1_POLICY_TYPES",
    "bev_payload_bytes",
    "build_stage1_policy_graph",
    "collate_stage1_samples",
    "enumerate_stage1_policies",
    "evaluate_stage1_uncertainty_rows",
    "add_metric_delta",
    "init_encoder_from_stage1",
    "load_policy_uncertainty_csv",
    "make_stage1_policy_metadata",
    "make_stage1_sample",
    "objlist_payload_bytes",
    "policy_label",
    "policy_key",
    "policy_to_dict",
    "summarize_policies",
    "valid_object_ids",
    "visible_object_ids_by_vehicle",
    "wam_stage1_configs_from_env",
    "write_policy_uncertainty_html",
    # per-step cooperative-graph timeline visualization
    "BevOptions",
    "append_record_jsonl",
    "group_records_to_frames",
    "hetero_graph_to_record",
    "layout_layered",
    "load_records_jsonl",
    "render_graph_matplotlib",
    "write_graph_frames_png",
    "write_graph_timeline_gif",
    "write_graph_timeline_html",
]
